use fs_err::{self, File};
use std::{
    env,
    error::Error,
    io::{self, Read},
    path::Path,
    process::{Command, Stdio},
    str::FromStr,
};

use build_rs::{input, output};
use flate2::read::GzDecoder;

/// # Example file
///
/// ```txt
/// go1.26.3
/// time 2026-05-04T20:36:18Z
/// ```
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct VersionFile {
    version: String,
    time: Option<String>,
}

impl FromStr for VersionFile {
    type Err = Box<dyn Error>;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let mut lines = s.lines();
        let version = lines.next().ok_or("missing version")?.to_string();
        let mut time: Option<String> = None;
        for line in lines {
            let parts = line.splitn(2, ' ').collect::<Vec<_>>();
            if parts.len() == 0 {
                continue;
            }
            if parts[0] == "time" {
                if parts.len() != 2 {
                    return Err("invalid time line".into());
                }
                time = Some(parts[1].to_string());
            }
        }
        Ok(Self { version, time })
    }
}

fn clean(dir: impl AsRef<Path>) -> Result<(), Box<dyn Error>> {
    let dir = dir.as_ref().canonicalize()?;
    eprintln!("Cleaning {}...", dir.display());
    _ = fs_err::remove_dir_all(dir.join("bin"));
    _ = fs_err::remove_dir_all(dir.join("pkg"));
    for path in fs_walk::WalkOptions::new().walk(dir.join("src")).flatten() {
        let path_file_name = path
            .file_name()
            .ok_or("invalid file name")?
            .to_str()
            .ok_or("invalid file name")?;
        if path.is_dir() {
            let binary_path = path.join(path_file_name);
            if binary_path.is_file() {
                fs_err::remove_file(&binary_path)?;
            }
            _ = fs_err::remove_file(binary_path.with_added_extension("exe"));
        } else if !path.is_dir() && path_file_name.starts_with("z") {
            let file = File::open(&path)?;
            let mut head = Vec::new();
            file.take(512).read_to_end(&mut head)?;
            if let Ok(head_str) = String::from_utf8(head) {
                const GENERATED: &str = r#"// Code generated by 'simdgen -o godefs -goroot $GOROOT -xedPath $XED_PATH go.yaml types.yaml categories.yaml'; DO NOT EDIT."#;
                if head_str.starts_with(GENERATED) {
                    fs_err::remove_file(&path)?;
                }
            }
        }
    }
    _ = fs_err::remove_file(dir.join("VERSION.cache"));
    Ok(())
}

fn make(src_dir: impl AsRef<Path>, restore: bool) -> Result<(), Box<dyn Error>> {
    let src_dir = src_dir.as_ref().canonicalize()?;
    if restore {
        clean(src_dir.join(".."))?;

        let version_file: VersionFile =
            fs_err::read_to_string(src_dir.join("../VERSION"))?.parse()?;
        eprintln!("VERSION: {}", &version_file.version);

        // TODO: Dynamically determine $GOOS/$GOARCH based on $CARGO_CFG_TARGET_OS and $CARGO_CFG_TARGET_ARCH
        let target_goos = "linux";
        let target_goarch = "amd64";

        let source_archive_url = format!("https://go.dev/dl/{}.src.tar.gz", &version_file.version);
        let platform_archive_url = format!(
            "https://go.dev/dl/{}.{}-{}{}",
            &version_file.version,
            &target_goos,
            &target_goarch,
            if target_goos == "windows" {
                ".zip"
            } else {
                ".tar.gz"
            }
        );
        let toolchain_info_url = format!(
            "https://go.dev/dl/mod/golang.org/toolchain/@v/v0.0.1-{}.{}-{}.info",
            &version_file.version, &target_goos, &target_goarch
        );
        let toolchain_mod_url = format!(
            "https://go.dev/dl/mod/golang.org/toolchain/@v/v0.0.1-{}.{}-{}.mod",
            &version_file.version, &target_goos, &target_goarch
        );
        let toolchain_zip_url = format!(
            "https://go.dev/dl/mod/golang.org/toolchain/@v/v0.0.1-{}.{}-{}.zip",
            &version_file.version, &target_goos, &target_goarch
        );

        let platform_archive_path = src_dir.join("../pkg/distpack").join(format!(
            "{}.{}-{}{}",
            &version_file.version,
            &target_goos,
            &target_goarch,
            if target_goos == "windows" {
                ".zip"
            } else {
                ".tar.gz"
            }
        ));
        if !platform_archive_path.try_exists()? {
            fs_err::create_dir_all(platform_archive_path.parent().ok_or("invalid path")?)?;

            let mut response = reqwest::blocking::get(&platform_archive_url)?.error_for_status()?;
            let mut file = File::create(&platform_archive_path)?;
            io::copy(&mut response, &mut file)?;
        }

        if platform_archive_path.ends_with(".zip") {
            let mut platform_archive = zip::ZipArchive::new(File::open(&platform_archive_path)?)?;
            for i in 0..platform_archive.len() {
                let mut source_file = platform_archive.by_index(i)?;
                let source_file_name = source_file
                    .enclosed_name()
                    .ok_or("invalid file name in zip")?;
                let path = src_dir
                    .join("..")
                    .join(source_file_name.strip_prefix("go")?);
                if !path.try_exists()? {
                    if source_file.is_dir() {
                        fs_err::create_dir_all(&path)?;
                    } else if source_file.is_file() {
                        if let Some(parent) = path.parent() {
                            fs_err::create_dir_all(parent)?;
                        }
                        let mut destination_file = File::create(&path)?;
                        io::copy(&mut source_file, &mut destination_file)?;
                    } else {
                        return Err(format!(
                            "unsupported file type in zip: {}",
                            source_file_name.display()
                        )
                        .into());
                    }
                }
            }
        } else {
            let mut platform_archive =
                tar::Archive::new(GzDecoder::new(File::open(&platform_archive_path)?));
            for entry in platform_archive.entries()? {
                let mut entry = entry?;
                let path = src_dir.join("..").join(entry.path()?.strip_prefix("go")?);
                if !path.try_exists()? {
                    entry.unpack(&path)?;
                }
            }
        }

        let source_archive_path = src_dir
            .join("../pkg/distpack")
            .join(format!("{}.src.tar.gz", &version_file.version));
        if !source_archive_path.try_exists()? {
            let mut response = reqwest::blocking::get(&source_archive_url)?.error_for_status()?;
            let mut file = File::create(&source_archive_path)?;
            io::copy(&mut response, &mut file)?;
        }

        let toolchain_info_path = src_dir.join("../pkg/distpack").join(format!(
            "v0.0.1-{}.{}-{}.info",
            &version_file.version, &target_goos, &target_goarch
        ));
        if !toolchain_info_path.try_exists()? {
            let mut response = reqwest::blocking::get(&toolchain_info_url)?.error_for_status()?;
            let mut file = File::create(&toolchain_info_path)?;
            io::copy(&mut response, &mut file)?;
        }

        let toolchain_mod_path = src_dir.join("../pkg/distpack").join(format!(
            "v0.0.1-{}.{}-{}.mod",
            &version_file.version, &target_goos, &target_goarch
        ));
        if !toolchain_mod_path.try_exists()? {
            let mut response = reqwest::blocking::get(&toolchain_mod_url)?.error_for_status()?;
            let mut file = File::create(&toolchain_mod_path)?;
            io::copy(&mut response, &mut file)?;
        }

        let toolchain_zip_path = src_dir.join("../pkg/distpack").join(format!(
            "v0.0.1-{}.{}-{}.zip",
            &version_file.version, &target_goos, &target_goarch
        ));
        if !toolchain_zip_path.try_exists()? {
            let mut response = reqwest::blocking::get(&toolchain_zip_url)?.error_for_status()?;
            let mut file = File::create(&toolchain_zip_path)?;
            io::copy(&mut response, &mut file)?;
        }
    } else {
        let program = if input::cargo_cfg_windows() {
            "./make.bat"
        } else {
            "./make.bash"
        };
        let status = Command::new(program)
            .current_dir(&src_dir)
            .args(&["-distpack"])
            .stdin(Stdio::null())
            .stdout(io::stderr())
            .stderr(io::stderr())
            .status()?;
        if !status.success() {
            return Err(format!("failed to build Go: {}", status).into());
        }
    }
    Ok(())
}

fn main() -> Result<(), Box<dyn Error>> {
    output::rerun_if_env_changed("DOIT");
    let restore = true;
    let doit = env::var("DOIT")
        .map(|v| v == "1" || v.to_lowercase() == "true")
        .unwrap_or_default();
    if doit {
        make("go/src", restore)?;

        let mut my_archive = zip::ZipWriter::new(File::create(input::out_dir().join("go.zip"))?);
        let mut platform_archive = tar::Archive::new(GzDecoder::new(File::open(
            Path::new("go")
                .join("pkg/distpack")
                .join("go1.26.3.linux-amd64.tar.gz"),
        )?));
        for entry in platform_archive.entries()? {
            let mut entry = entry?;
            let header = entry.header();
            let entry_path = entry.path()?;
            let my_path_str = entry_path.strip_prefix("go")?.to_str().ok_or("invalid path")?;
            let options = zip::write::SimpleFileOptions::default().unix_permissions(header.mode()?);
            if header.entry_type().is_dir() {
                my_archive.add_directory(my_path_str, options)?;
            } else {
                my_archive.start_file(my_path_str, options)?;
                io::copy(&mut entry, &mut my_archive)?;
            }
        }
        my_archive.finish()?;
    }

    Ok(())
}
